### ISSUE TITLE
icat display image in 24 bit

### ISSUE THREAD

**Issue by Morpheus3000** [atextor/icat#13]
I just came across icat. I am using Arch Linux. I tried displaying an image with icat, but it always displays in 256 colour, instead of 24 bit.
![image](https://user-images.githubusercontent.com/16116047/35815736-7da89052-0a99-11e8-9e35-756a5f53c55d.png)

My terminal already supports 24 bit colour as can be seen from the following test:

![image](https://user-images.githubusercontent.com/16116047/35815802-a97ab9c6-0a99-11e8-8256-b56fad66d701.png)

I tried searching the internet for enabling 24 bit colour support for icat, but all I could up with is that it is supported by default in icat.
So my question is how do I get the pictures to display in 24 bit colour.

**Comment by atextor** [comment]
Hi, icat by default uses indexed (256 colors) mode. To enable 24bits, use the switch '-m 24bit' or '-m both'.

**Comment by Morpheus3000** [comment]
Hi!
Thanks for the reply! I tried it with that switch, but the results seems pixelated. Is there anyway to get around it? I am looking for an effect similar to imgcat that is available on iterm. Seems to me icat resizes the image and then upscales it to terminal size causes it to become pixelated. (I am just speculating, I might be completely wrong here in this assumption.)

**Comment by atextor** [comment]
The results are pixelated, because icat uses the Unicode box characters ▀ and ▄ with the right foreground and background color escapes to draw images, as there is no standard way to output actual images in terminal. There are ways to achieve what you want on Linux, they depend on which terminal emulator you use, though.

- You can use [terminology](https://www.enlightenment.org/about-terminology) and its special `tycat` tool to output images
- mlterm and xterm (compiled with --enable-sixel-graphics option and started with `-ti vt340` option) support [libsixel](https://github.com/saitoha/libsixel), where you can use `img2sixel` to output images
- Someone also wrote a [patch](https://gist.github.com/saitoha/be56f3b58c5212abe3f76a13578a548d) to support libsixel in urxvt
